sudo: enabled

dist: xenial

language: generic

branches:
  only:
    - master

before_install:
  - sudo apt-get install -y lynx

install:
  - bash getlunchmenu.bash

after_success:
  - cat README.md

